aws-samples/eks-saas-gitops

gitops/application-plane/production/pooled-envs/pool-1.yaml, gitops/application-plane/production/tenants/TENANT_TEMPLATE_HYBRID.yaml, gitops/application-plane/production/tenants/TENANT_TEMPLATE_POOL.yaml, gitops/application-plane/production/tenants/TENANT_TEMPLATE_SILO.yaml, gitops/application-plane/production/tenants/tenant-1-siloed.yaml, tenant-chart/values.yaml.template
=> feat: Helm chart & release template cleanup

gitops/control-plane/production/workflows/kustomization.yaml, gitops/infrastructure/production/06-argo-events.yaml.template, install.sh, terraform/clusters/production/outputs.tf
=> bugfix: fixed typo

install.sh
=> bugfix: Added Argo Events IRSA

gitops/control-plane/production/workflows/tenant-onboarding-sensor.yaml, install.sh
Fixing hard coded region in `gitops/control-plane/production/workflows/tenant-onboarding-sensor.yaml` file.
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
name: aws-sqs
namespace: argo-events
spec:
template:
serviceAccountName: argo-events-sa
sqs:
tenant-provisioning:
jsonBody: true
region: "${AWS_REGION}"
queue: "argoworkflows-queue"
```
Adding sed for `install.sh`
```
sed -e "s|{AWS_REGION}|${AWS_REGION}|g" "${GITOPS_FOLDER}/control-plane/production/workflows/tenant-onboarding-sensor.yaml"
```
=> fix: Adding $AWS_REGION env sed for `tenant-onboarding-sensor.yaml`

.gitignore, README.md, cleanup.sh, gitops/application-plane/production/pooled-envs/pool-1.yaml, helpers/cloudformation.yaml, install.sh
Added ./kube to .gitignore
Remove stack steps on README
Changes to cleanup.sh -- manually removing resources (S3, ECR, code-commit-user ssh key), uninstalling resources with Flux, then terraform
deploy ingress true on pool-1, so we can bind this helmrelease with the creation of the ALB - this simplifies cleanup
Custom resource lambda deletion invokes cleanup.sh through SSM
CFN status fix on error on install.sh
=> Stack cleanup script

tenants-microsservices/consumer/buildspec.yml, tenants-microsservices/consumer/requirements.txt, tenants-microsservices/producer/buildspec.yml, tenants-microsservices/producer/requirements.txt, terraform/clusters/production/pipelines.tf, terraform/modules/codebuild/main.tf, terraform/modules/codebuild/outputs.tf, terraform/modules/codebuild/vars.tf, terraform/modules/codepipeline/main.tf, terraform/modules/codepipeline/vars.tf
Added modules for CodeBuild and CodePipeline, used those modules to provision the CI pipelines for producer and consumer microservices.
=> Feat: Pipelines for consumer and producer

install.sh, tenant-onboarding/02-tenant-onboarding-infra.sh, terraform/application-plane/production/environments/pooled-1.tf, terraform/application-plane/templates/hybrid-template.tf.template, terraform/application-plane/templates/pool-template.tf.template, terraform/application-plane/templates/silo-template.tf.template
Included Tag of repository during install.sh, start to use Tag as source for terraform modules, that way we can version chart and infra package together
=> Feat: Added support for terraform module source as Git

tenants-microsservices/consumer/consumer.py, tenants-microsservices/producer/producer.py
Changing microsservice version to match Helm chart and terraform version.
=> fix: microsservice app version

install.sh, tenants-microsservices/payments/Dockerfile, tenants-microsservices/payments/buildspec.yml, tenants-microsservices/payments/payments.py, tenants-microsservices/payments/requirements.txt, terraform/application-plane/templates/pool-template.tf.template, terraform/clusters/production/outputs.tf, terraform/clusters/production/pipelines.tf, terraform/clusters/production/related_infra.tf, terraform/clusters/production/variables.tf, terraform/modules/tenant-apps/main.tf, terraform/modules/tenant-apps/variables.tf
Adding Payments microsservice infrastructure and application, also included the payments infrastructure into `tenant_apps` modules but commented, during Lab3 we will ask to remove the commentary and generate a new tag `v1.0.0`  
=> feat: Added support for payments microsservice

install.sh, terraform/clusters/production/related_infra.tf
Changed install.sh to match terraform module name
=> fix: Adjusted install.sh to match terraform module name

terraform/clusters/production/outputs.tf
Changed terraform `output` to match the module name.
=> Adjusted output to match module

gitops/application-plane/production/pooled-envs/pool-1.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_HYBRID.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_POOL.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_SILO.yaml
Updating chart version to `{MAJOR_VERSION}.0.x` on `/gitops/application-plane/templates` and `/gitops/application-plane/production/pooled-envs`.
=> fix: Updating templates version to `MAJOR.0.x`

install.sh
Adding  `-target=aws_ecr_repository.payments_container` to `terraform apply`
=> fix: Update install.sh with `aws_ecr_repository.payments_container`

terraform/application-plane/production/environments/pooled-1.tf
Remove duplicate provider and change tenant_id to `pooled-1` from `terraform/application-plane/production/environments/pooled-1.tf`
=> fix: remove duplicate provider

install.sh
=> Added payments_container in terraform apply

gitops/control-plane/production/workflows/tenant-deployment.yaml, workflow-scripts/04-tenant-deployment-infra.sh
Changed infra deployment script to sed correct tenant-id
=> fix: Deployment infra script changes

gitops/application-plane/production/pooled-envs/pool-1.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_HYBRID.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_SILO.yaml, gitops/control-plane/production/workflows/tenant-deployment.yaml, install.sh, tenant-chart/templates/deployment.yaml, tenant-chart/values.yaml.template, terraform/application-plane/production/environments/pooled-1.tf, terraform/application-plane/templates/hybrid-template.tf.template, terraform/application-plane/templates/silo-template.tf.template, terraform/modules/tenant-apps/main.tf, terraform/modules/tenant-apps/outputs.tf, workflow-scripts/03-tenant-onboarding.sh, workflow-scripts/04-tenant-deployment-infra.sh
=> Added terraform resource ARNs to deployments as env vars

gitops/application-plane/production/pooled-envs/pool-1.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_HYBRID.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_SILO.yaml, install.sh, tenant-chart/templates/deployment.yaml, tenant-chart/values.yaml.template, terraform/modules/tenant-apps/data.tf, terraform/modules/tenant-apps/main.tf, workflow-scripts/03-tenant-onboarding.sh
=> Added resource ARN as parameters

terraform/application-plane/production/environments/pooled-1.tf, terraform/application-plane/templates/hybrid-template.tf.template, terraform/application-plane/templates/silo-template.tf.template, terraform/modules/tenant-apps/outputs.tf
=> fix: typo in tf outputs

terraform/modules/tenant-apps/main.tf
=> fix: typo in tf parameters

gitops/application-plane/templates/TENANT_TEMPLATE_HYBRID.yaml, terraform/application-plane/templates/hybrid-template.tf.template, terraform/modules/tenant-apps/data.tf, terraform/modules/tenant-apps/main.tf
=> feat: Added parameter store per tenant

gitops/application-plane/production/pooled-envs/pool-1.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_HYBRID.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_SILO.yaml, install.sh, terraform/application-plane/production/environments/pooled-1.tf, terraform/application-plane/templates/hybrid-template.tf.template, terraform/application-plane/templates/pool-template.tf.template, terraform/application-plane/templates/silo-template.tf.template, terraform/modules/tenant-apps/main.tf, terraform/modules/tenant-apps/outputs.tf, workflow-scripts/03-tenant-onboarding.sh, workflow-scripts/Dockerfile
Tested for Silo and Pool model.
TODO: Implement Hybrid model
=> Added IRSA for microservices

tenant-chart/templates/deployment.yaml, tenants-microsservices/consumer/consumer.py, tenants-microsservices/consumer/requirements.txt, tenants-microsservices/producer/producer.py, tenants-microsservices/producer/requirements.txt, terraform/modules/tenant-apps/main.tf
New microservice code
- GET /producer-- echoes version
- POST /producer -- puts message on q
- GET /consumer -- echoes version
- Consumer loops to query q on separate thread and pushes messages to DDB once processed
- Both microservices rely on SSM to get (SQS Q, producer) and (SQS Q, DynamoDB table, producer)
- Producer based on inbound header tenantID
- Consumer based on tenant deployment environment 
- Changed DDB table schema (tenant_id PK, message_id, SK)
- Changed environment variable that described the tenant deployment environment on microservices to ENVIRONMENT
=> New microservices

gitops/application-plane/production/pooled-envs/pool-1.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_HYBRID.yaml, gitops/application-plane/templates/TENANT_TEMPLATE_SILO.yaml, terraform/modules/tenant-apps/main.tf
Tested all three models: Silo, Pool, and Hybrid
=> Added support for Hybrid model on microservices IRSA

terraform/clusters/production/related_infra.tf
=> fix: least privilege

install.sh, terraform/modules/tenant-apps/data.tf
Removing the folders after container images are built
Added missing data object to terraform app plane
=> Install fix

terraform/clusters/production/related_infra.tf
Fix: Changed SQS permissions on Terraform
=> fix: Adjusted permissions

terraform/modules/tenant-apps/README.md, terraform/modules/tenant-apps/data.tf, terraform/modules/tenant-apps/main.tf, terraform/modules/tenant-apps/outputs.tf
Fix Terraform syntax
* Formatting files
* Linting terraform code
* Update `tenant-apps` README.
=> fix: Terraform code

gitops/control-plane/production/workflows/tenant-onboarding-sensor.yaml, gitops/control-plane/production/workflows/tenant-onboarding-workflow-template.yaml, workflow-scripts/sec/00-validate-tenant.sh
Added tenant validation during on-boarding, using `tenant_id` to validate if a tenant already exists or not, based on name convention.
=> feat: Added validation step to on-boarding

tenant-microservices/payments/payments.py
=> fixed payments service name

gitops/control-plane/production/applications/00-onboarding-service.yaml, gitops/control-plane/production/applications/kustomization.yaml, gitops/infrastructure/base/sources/application-chart-helm.yaml.template, helm-charts/application-chart/.helmignore, helm-charts/application-chart/Chart.yaml, helm-charts/application-chart/templates/NOTES.txt, helm-charts/application-chart/templates/_helpers.tpl, helm-charts/application-chart/templates/deployment.yaml, helm-charts/application-chart/templates/hpa.yaml, helm-charts/application-chart/templates/ingress.yaml, helm-charts/application-chart/templates/service.yaml, helm-charts/application-chart/templates/serviceaccount.yaml, helm-charts/application-chart/templates/tests/test-connection.yaml, helm-charts/application-chart/values.yaml, terraform/modules/gitops-saas-infra/apps_needs.tf, terraform/modules/gitops-saas-infra/outputs.tf, terraform/modules/gitops-saas-infra/variables.tf, terraform/workshop/outputs.tf, terraform/workshop/templating.sh
=> Added support for Application Chart

terraform/modules/gitops-saas-infra/variables.tf
=> added default value

terraform/workshop/main.tf
=> fix hardcode kms

terraform/modules/codebuild/versions.tf, terraform/modules/codepipeline/versions.tf, terraform/modules/flux_cd/versions.tf, terraform/modules/tenant-apps/versions.tf, terraform/workshop/main.tf
=> Fixed module versions
